/*
 *     Copyright (C) 2026 Valeri Gokadze
 *
 *     Catchify is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Catchify is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 *     For more information about Catchify, including how to contribute,
 *     please visit: https://github.com/thamodharangm/catchify
 */

List<Map<String, dynamic>> artistsDB = [
  // Tamil Artists
  {
    'ytid': 'UCbRSywya_rl8YS15Lo9ttsA',
    'title': 'Anirudh Ravichander',
    'image': 'https://lh3.googleusercontent.com/wBG4jypwBcEGHd-qSbM2_4B46WPEhlOCjusCOEkxdnsoIC4WLS9LmFARZsE854pB-vAEYlsp4x2yiHE=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCtJe0RYzgPddQXKtWduxz_w',
    'title': 'A. R. Rahman',
    'image': 'https://yt3.googleusercontent.com/vHMOuDn8gr3SW9Pm8yFgmtYzM5kj4ayng5HKRjW0OyjG9mPK923XMVtTZTt4NUG_1aemWNLSQ27zjtA=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCwzzSiogpjsYBMoyVcwDXwQ',
    'title': 'Ilaiyaraaja',
    'image': 'https://lh3.googleusercontent.com/QxbV6wK_wcQWcBY9rBicZlsl1-gX5M6nGjfNN3BTzgknhaSJ6yhnHW7NmF4dTx0Ch9g9-VTD6YUD2crW=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCQXg6kTstIOwbrjBwE3IlDw',
    'title': 'Yuvan Shankar Raja',
    'image': 'https://lh3.googleusercontent.com/-IRVL5B0n7-V9Gh9XZvQG161HYqkH_SNSHfJwWYeIcVVh35sMq9-jHTk1FCeAmeUHSdEq7UMpoVzUPw=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCv6xCP3bn5Pdq0E4SJ4iEKg',
    'title': 'Harris Jayaraj',
    'image': 'https://yt3.googleusercontent.com/uGytpfjALdTSzoh2hU7FJAqTRrhgWy0Qrio8wrpzRKwAeREv4yBQJpXm-KcOLM3LJW9VQKRNdaeXrL4=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC7_KgmSrwM247k2lnh5GhHw',
    'title': 'Sid Sriram',
    'image': 'https://yt3.googleusercontent.com/Ip35qauI_vMztXkJ3Wd6etvLwiyRrHIGvDyKK3714vyWMBx1ogHxPxkA8ohPnOLyy68wzEVBblPmsHHU=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCAMJ6FZcDvdrSRoYcZ14x1Q',
    'title': 'Santhosh Narayanan',
    'image': 'https://yt3.googleusercontent.com/YfMj32x0B85XqpZCgWu1KXSSXsy8t4Ajt3GUIJw5oLLU94for_wN4HMDQYNvO3U-Hou1TiML9w=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC0tPcuSe25Ly0wksSzN4iKg',
    'title': 'Pradeep Kumar',
    'image': 'https://yt3.googleusercontent.com/g5vebpXaepoLnJv5fBGFmZB1NDwy8IK6VC4BK-iAOnHjdO57Fbg8py5XkgGkJ_S-hNd2_2lW=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCK-E95XlAlzJtXKIrF4-hjA',
    'title': 'G. V. Prakash Kumar',
    'image': 'https://yt3.googleusercontent.com/jEh-GLa0VeT7J8D3IhnDH9WqfdPNTp0OthFle0NNtpU6b2nVHUr3vS_trVXlBeYROz-36bAQYw=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCm9LbLvK2bAy3pemdtduZCw',
    'title': 'D. Imman',
    'image': 'https://yt3.googleusercontent.com/vyWvssNMFaoGKP2VQvVrWMcsUotLTZfzp4-nGsMEbSAngEJBvXCMEo6rbM1di1kYkTz88zbNGiaabxI=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCl4iPtukwe7m0kIxUMskkgA',
    'title': 'S. P. Balasubrahmanyam',
    'image': 'https://yt3.googleusercontent.com/i-PUJfHy7H3_s1AUBWUaulTzhclF5MobqSIw_3nM3a2-kfCGsY_67K-dEOW7baAiBdfHvSOuHVjR_g=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCWUjYIas3aSW65lQOpGiRrg',
    'title': 'K. J. Yesudas',
    'image': 'https://yt3.googleusercontent.com/R6D0x83Uvnnhdy55hbdpi4SS0I3xqYZsqr_WcsGY0SlQOimmh2HJrkq3KMunG0l9ymm1gGbvtYp_HJw=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCrC-7fsdTCYeaRBpwA6j-Eg',
    'title': 'Shreya Ghoshal',
    'image': 'https://yt3.ggpht.com/PgINZNe0qVxgMSXKG5vF82bNN4WCC12zgWsz9I7OLs4CLF9Cn0Vxq7Xc1ToupnzXrCv0nKfe3VM=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC3eFGgfV2cvYB_0cQnh_omg',
    'title': 'Jonita Gandhi',
    'image': 'https://yt3.googleusercontent.com/4Yatmgs4H-T4qs-kDh3y3N3C7t7bI6yYQo8dTeiyBLLvIRyiD3XvyU3KlFxfNddxDqfygApdl3Je6u3I=w540-h540-p-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCf1p1hGlMCmuq-jIMjLNk0w',
    'title': 'Haricharan',
    'image': 'https://yt3.googleusercontent.com/3OxqzMOveOAdURinww61-M1YKCd2hcKMhBEu4zDZrI0iAWFdZLhRseRdVt0R-DM1o0H565opsw=w540-h540-l90-rj',
    'language': 'Tamil',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // English / Global Artists
  {
    'ytid': 'UClYV6hHlupm_S_ObS1W-DYw',
    'title': 'The Weeknd',
    'image': 'https://lh3.googleusercontent.com/U-SAmNOu4TynE818gLCfKsuHZ0U5YNEtO9mrjSI9WCCKERs98LzrCal5kajBBTQNwdcisoB2Bn-pHp4=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCPC0L1d253x-KuMNwa05TpA',
    'title': 'Taylor Swift',
    'image': 'https://yt3.googleusercontent.com/RCpTA6EXJQyjVFDosWOKa2SMmqkua_lA9mHPDWWciLwgqpZLz-k8rXWRF_367trrQ7up9BUwCbk6kRk=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UClmXPfaYhXOYsNn_QUyheWQ',
    'title': 'Ed Sheeran',
    'image': 'https://lh3.googleusercontent.com/jQoBIAS6JjFGpcqQY1M_Mh3AasOvFENCdVRxkgax1a0K6qiq7AgE3MbJ6Jtt-Jndcarvoawmrg66KTny=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCERrDZ8oN0U_n9MphMKERcg',
    'title': 'Billie Eilish',
    'image': 'https://lh3.googleusercontent.com/tQC4rOL6xz6FhmFr0ggQExxyGbYSOsyveXVSnPBh2WjEyIzQ9pMHablLJ-0GlMBrLBlBrbWQGmzrV6KN=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCZn4r7heNOPY-C43YIywnVA',
    'title': 'Bruno Mars',
    'image': 'https://lh3.googleusercontent.com/hnefGBrazRhn4Z92bdSZBUENl40ONjRiVDsmZKZh-WZ2iCKE-2c7KKR7SNcZfzLHoRyB3E6as8L87YA=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCzVb0SIXp9q9PeKCcFjsBtA',
    'title': 'Dua Lipa',
    'image': 'https://lh3.googleusercontent.com/aFx8s1fTuelgxONGbezmTG0EKR8r82uB5H-Q6ZJtssyCWLJWF8GfZNr4tHo84sXdFCPBKrA4R6zXOss=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCGvj8kfUV5Q6lzECIrGY19g',
    'title': 'Justin Bieber',
    'image': 'https://lh3.googleusercontent.com/4ULlRiFBFglNemZJyKn6_e2-iOIdJEbgBgq_79RQclndG6pge0yGgS2k2On6E1FkCJzenyHkHRzkvjFp=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCU6cE7pdJPc6DU2jSrKEsdQ',
    'title': 'Drake',
    'image': 'https://yt3.googleusercontent.com/MxNjcRJ-uK4Xvx7u90IhEFLQM8x9LIGTA9VCKHq5U4Wn2jOgiWaMtg-qz329SIzqnCyhdCCB3MpdAGs=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCyD3XWRK9ko-izf2nBSFitw',
    'title': 'Post Malone',
    'image': 'https://lh3.googleusercontent.com/48LfK4z6o-CCEWgHQnQfg0ltcT9tbZSN0qjSh0FSJsJI5GF48j2-pH219ciG1ML-PI80ZGD4Vz6sjg=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC0076UMUgEng8HORUw_MYHA',
    'title': 'Ariana Grande',
    'image': 'https://yt3.googleusercontent.com/DU6Kpr5TYKcW6QHvMnsJau5_8QSuix8LCLtf5UEaziZZdXw8SxvcxJ9YWmVIQuzhg2R-MVHYgjdGCQ=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCIaFw5VBEK8qaW6nRpx_qnw',
    'title': 'Coldplay',
    'image': 'https://lh3.googleusercontent.com/IOKuXtp8PCQ_Fc-vaRKm3sKIXBxFV51gZheLTH5br-YGnWHFQf_Jywcuk7wbprYRoEbQyS_XZY6-nMJX=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCedvOgsKFzcK3hA5taf3KoQ',
    'title': 'Eminem',
    'image': 'https://lh3.googleusercontent.com/JFI6JZrS-Lco4UdpqDfHY5Wgwy51VXWxmNdI7bCBU5CDlIpN6WWyisZ7MGlpjbrxEGYMFpsqoR_UwcE=w540-h540-p-l90-rj',
    'language': 'English',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // Hindi Artists
  {
    'ytid': 'UCDxKh1gFWeYsqePvgVzmPoQ',
    'title': 'Arijit Singh',
    'image': 'https://lh3.googleusercontent.com/W_yOqnKSDYyeVOY_AsXhuAtb6rW3vCL3GtJ9DA1GxWOrJfyeSOqzvTv_TkFHijdkVPXWutASBlRFPg=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCCTN01plFzn4npREHKT2_9Q',
    'title': 'Pritam',
    'image': 'https://yt3.googleusercontent.com/sjGMYJQ1J3FZEIBsMYUztMjjYOM4-NJ24CjmIHqxTWCxAM1YgjL-d_17u7_PRhTouOwwAjbu-2x5S6I=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCVGomUS__PL0c4jDXa0QwXA',
    'title': 'Atif Aslam',
    'image': 'https://yt3.googleusercontent.com/ykJkyILKum4B2oudDxjnf5WNenWWZAp-WEz0_CHp4cu0VnqB2-uaNDylItqC68WLXV62rdHDun-ahbg=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCsmm-jjSLILh12mZ2aR6Qrg',
    'title': 'Neha Kakkar',
    'image': 'https://lh3.googleusercontent.com/fV2lMYLeaJc9jxta-eXfwHhvfQHCk9c6HgTVw8MqiGasI-kZQ8qbkuHnrTcXIhzkfmwGfMxwFbI-4CU=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCVfSAUepe_FzP6ge6WexO5Q',
    'title': 'Badshah',
    'image': 'https://lh3.googleusercontent.com/bbR8znm7CX07mCGQH-M484ckFRaKkSmTjwrwuFZxQUBy7Uc5gQcintkpqDXCuSX0DdLLg2aPskZhC2s=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCsC4u-BJAd4OX1hJXtwXSOQ',
    'title': 'Sonu Nigam',
    'image': 'https://lh3.googleusercontent.com/iWH_XSIO8yZvIqz8vxkwC9BjzGM4giAhR69Z6LZ0t8Rp79ASNFVwpwHZWOyyo94B_jsXl8HtFueMgMA=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCdWuR07og626xwU93eSCh9A',
    'title': 'Jubin Nautiyal',
    'image': 'https://lh3.googleusercontent.com/4Jd9XSimz29-o12oJKUmgfTx3otHBHlTy0jb3Ace4ti2bz8Nuo59IeneNlM9EKRQXNRpLwk6YoEuNQ=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC41L0sFqy6_Q43RGgUnJ75Q',
    'title': 'Sunidhi Chauhan',
    'image': 'https://lh3.googleusercontent.com/_c102EBASHERqDnrU32iygceCB0ItZy5PSeR6rvnKEusmQWNZhZRcp_xdlZHS578a82QVSPKfOyrzn8=w540-h540-p-l90-rj',
    'language': 'Hindi',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // Telugu Artists
  {
    'ytid': 'UCwHleA-qNWiMl05mwTDbuWA',
    'title': 'Devi Sri Prasad',
    'image': 'https://yt3.googleusercontent.com/Jn3s6U5foBczx3HoJuiVN6euF7QRB1b8rsp3lecxZ7EwumQ-27E_iR2uu8fJV0H6cctb74s5nut_dhM=w540-h540-p-l90-rj',
    'language': 'Telugu',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCLnRv17aPDpTM_Z_2nHFikA',
    'title': 'Thaman S',
    'image': 'https://yt3.googleusercontent.com/1u69o5eBH1yxnBh5QZ65vkQGwmgdwVv-ILISp-MLhkpXHK7AXgE52JbouQpDMhvDRwpHy3By6ETcRA4=w540-h540-l90-rj',
    'language': 'Telugu',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCuO2zYTV1HzP9D6Dei_3-aA',
    'title': 'M. M. Keeravani',
    'image': 'https://yt3.googleusercontent.com/Qup-E04agly41Cgzuuzu2XBgWjebBgRFHHJWhninTBx2hEfrVVQ7RNw4HEJzPmOUohi78l0if9ZzreFn=w540-h540-l90-rj',
    'language': 'Telugu',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCK5zappMYMGEvFBGxR7md6g',
    'title': 'Ram Miriyala',
    'image': 'https://yt3.googleusercontent.com/C6ZgYX28bO6D8qQxEZ_RYz90PkFYL9byd6xCUIZW4M016lMI4-LxD-BBakbSid_9e9d0PTK9HLqR7iDs=w540-h540-l90-rj',
    'language': 'Telugu',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCp6JQUPuvQdNUM50_ekcVfg',
    'title': 'Anurag Kulkarni',
    'image': 'https://yt3.googleusercontent.com/63T2Aq52wrRMDLUhnT8RbqqfWi4NF3NtAVtLNuitM9vnzmd0ZiQrCmUURxOW_H3svAJVrKRtE_YhG9gg=w540-h540-p-l90-rj',
    'language': 'Telugu',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // Malayalam Artists
  {
    'ytid': 'UCzpmF_8698JYBqh96PPCTfw',
    'title': 'Sushin Shyam',
    'image': 'https://yt3.googleusercontent.com/YlcHWu5-x5LKoVkv80_D533SdNG_mly1WtLAkcUcFwuVGWSHgU_q-3-SFQgj8XXg8q8UZXPacg=w540-h540-l90-rj',
    'language': 'Malayalam',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UC0aV0qinwdUmB2NuEhfRS_w',
    'title': 'Hesham Abdul Wahab',
    'image': 'https://yt3.ggpht.com/ytc/AIdro_mjy1zj7IVDhdBMkrH-Q4YBuXnatZ6iLMXLIrLE9fDxOg=w540-h540-l90-rj',
    'language': 'Malayalam',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCF35kALVhAo3kWiREPpkfmQ',
    'title': 'Jakes Bejoy',
    'image': 'https://yt3.googleusercontent.com/bj2lM5LJSK6HAtfeiFzHgVcVIejnwLEqjju1rBx9woij3D6t-3XIUsva3zzYoEh-sMz3f9Nt3p8_5RI=w540-h540-l90-rj',
    'language': 'Malayalam',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCi_tU7Hk8RjbffAxpjBYvCg',
    'title': 'K. S. Harisankar',
    'image': 'https://yt3.ggpht.com/ytc/AIdro_m1BynvBFb52BYjixx0qIygoVxxw9MfxF1fehzhdAR15Bw=w540-h540-l90-rj',
    'language': 'Malayalam',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // Punjabi Artists
  {
    'ytid': 'UCJ2m-WpROlZCiZZID9r7NSQ',
    'title': 'Diljit Dosanjh',
    'image': 'https://yt3.googleusercontent.com/7EYXXMXY594V8y4sZT2aawmdKgDAGTu5jNm9C-HpR3jY9cZJ0NMxS__nZKBdWZ1PUpJPjc2BAA=w540-h540-l90-rj',
    'language': 'Punjabi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCIOXXUXQ8y5ivei97JkiBAw',
    'title': 'Sidhu Moose Wala',
    'image': 'https://yt3.ggpht.com/ytc/AIdro_kiQJ0Hhp0O-tdaY1dy81-gSNujjccUlWstnpFr686ZlMk=w540-h540-l90-rj',
    'language': 'Punjabi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCQmNiXx378nooDuZPA2fTAg',
    'title': 'AP Dhillon',
    'image': 'https://lh3.googleusercontent.com/yJh1MZL2FvtJz3YeDAUhTRpfdUSwdotWw8XmB_An-4coKiVG4pDpUGRAPV7ooqmzBP4HAWrtjPyAfI4=w540-h540-p-l90-rj',
    'language': 'Punjabi',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCSmK5WX5U4gdtebWjoL81og',
    'title': 'Karan Aujla',
    'image': 'https://lh3.googleusercontent.com/k7sgqqcV5VScaMZtTmS8W_tfouLVBpgyJII0epYE2Vjw1-zzhGgUCV51aHxZn6cmZKKJgUfNlIVpZg=w540-h540-p-l90-rj',
    'language': 'Punjabi',
    'isArtist': true,
    'source': 'youtube-artist',
  },

  // Kannada Artists
  {
    'ytid': 'UCGCzMLhz0ucUUACQAHw-rmg',
    'title': 'Sanjith Hegde',
    'image': 'https://yt3.googleusercontent.com/oom6ZgCVlwOqUZauEjdzerUe00GdRfypxk9pUtkp2U7FiG1tD_uIbzAY90QCjXI-2LpxBNEx6g=w540-h540-l90-rj',
    'language': 'Kannada',
    'isArtist': true,
    'source': 'youtube-artist',
  },
  {
    'ytid': 'UCj1GW9LiAoZjPa0Jm067zdQ',
    'title': 'Raghu Dixit',
    'image': 'https://yt3.googleusercontent.com/u21sgfMobl5suRxyzSxPUYjKW14btJmWsjstDDAuex7G_JUCeQIy7IDHT_AkUUQ1joK7h4X6Mso=w540-h540-l90-rj',
    'language': 'Kannada',
    'isArtist': true,
    'source': 'youtube-artist',
  },
];
